#!/usr/bin/env node
// Collects the Playwright Copilot Test Agent files generated by
// `npx playwright init-agents --loop=copilot` and copies them into this
// plugin's `agents/` directory so they can be bundled and released.
//
// Playwright's generator has been known to write these files to different
// locations depending on version (e.g. `.github/agents/` or the repo root),
// so this script searches a set of known candidate directories and matches
// files by their well-known names.

import { existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

const AGENT_FILENAMES = [
  'playwright-test-generator.agent.md',
  'playwright-test-healer.agent.md',
  'playwright-test-planner.agent.md',
];

const CANDIDATE_DIRS = [
  repoRoot,
  join(repoRoot, '.github', 'agents'),
  join(repoRoot, '.copilot', 'agents'),
  join(repoRoot, 'agents'),
];

const destDir = join(repoRoot, 'agents');
if (!existsSync(destDir)) {
  mkdirSync(destDir, { recursive: true });
}

let copiedCount = 0;

for (const filename of AGENT_FILENAMES) {
  const sourceDir = CANDIDATE_DIRS.find((dir) => existsSync(join(dir, filename)));

  if (!sourceDir) {
    console.warn(`[collect-agents] Could not find generated file: ${filename}`);
    continue;
  }

  const sourcePath = join(sourceDir, filename);
  const destPath = join(destDir, filename);

  if (sourcePath === destPath) {
    console.log(`[collect-agents] Already in place: ${filename}`);
    continue;
  }

  copyFileSync(sourcePath, destPath);
  copiedCount += 1;
  console.log(`[collect-agents] Copied ${sourcePath} -> ${destPath}`);
}

if (copiedCount === 0) {
  console.warn('[collect-agents] No agent files were copied. Verify that `playwright init-agents --loop=copilot` ran successfully.');
} else {
  console.log(`[collect-agents] Done. Copied ${copiedCount} file(s) into ${destDir}`);
}
