#!/usr/bin/env node
// Collects the MCP server configuration generated by
// `npx playwright init-agents --loop=copilot` and merges it into this plugin's
// root `.mcp.json` so the Playwright MCP server is bundled alongside the
// hand-written servers (e.g. `db-cli`).
//
// Playwright's generator has been known to write this config to different
// locations depending on version (e.g. `.github/agents/mcp.json`, `.mcp.json`
// at the repo root), so this script searches a set of known candidate files
// and merges any Playwright server entries it finds.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

const destPath = join(repoRoot, '.mcp.json');

const CANDIDATE_FILES = [
  join(repoRoot, '.mcp.json'),
  join(repoRoot, '.github', 'agents', 'mcp.json'),
  join(repoRoot, '.github', 'mcp.json'),
  join(repoRoot, '.copilot', 'agents', 'mcp.json'),
  join(repoRoot, '.copilot', 'mcp.json'),
  join(repoRoot, 'mcp.json'),
];

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    console.warn(`[collect-mcp] Could not parse ${path}: ${error.message}`);
    return null;
  }
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isPlaywrightServer(name, server) {
  if (name.toLowerCase().includes('playwright')) {
    return true;
  }

  const haystack = JSON.stringify(server ?? '').toLowerCase();
  return haystack.includes('playwright');
}

const parsedConfig = existsSync(destPath) ? readJson(destPath) : null;
const existingConfig = isPlainObject(parsedConfig) ? parsedConfig : {};
const mergedServers = isPlainObject(existingConfig.mcpServers)
  ? { ...existingConfig.mcpServers }
  : {};

let mergedCount = 0;
let foundSource = false;

for (const candidate of CANDIDATE_FILES) {
  if (!existsSync(candidate)) {
    continue;
  }

  const config = readJson(candidate);
  const servers = isPlainObject(config) ? config.mcpServers : null;

  if (!isPlainObject(servers)) {
    continue;
  }

  for (const [name, server] of Object.entries(servers)) {
    if (!isPlaywrightServer(name, server)) {
      continue;
    }

    // The plugin's own `.mcp.json` is a candidate location, but servers already
    // merged into it are not new generator output.
    if (candidate === destPath) {
      continue;
    }

    foundSource = true;

    if (JSON.stringify(mergedServers[name]) === JSON.stringify(server)) {
      console.log(`[collect-mcp] Already up to date: ${name}`);
      continue;
    }

    mergedServers[name] = server;
    mergedCount += 1;
    console.log(`[collect-mcp] Merged server "${name}" from ${candidate}`);
  }
}

if (!foundSource) {
  console.warn(
    '[collect-mcp] No generated MCP config was found. Verify that `playwright init-agents --loop=copilot` ran successfully.',
  );
  process.exit(0);
}

if (mergedCount === 0) {
  console.log(`[collect-mcp] Done. ${destPath} is already up to date.`);
  process.exit(0);
}

const output = { ...existingConfig, mcpServers: mergedServers };
writeFileSync(destPath, `${JSON.stringify(output, null, 2)}\n`);
console.log(
  `[collect-mcp] Done. Merged ${mergedCount} server(s) into ${destPath}`,
);
